// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Data;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260331154145_AddAdminUser")]
    partial class AddAdminUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("WebAPI.Models.Entities.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AdminUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Quản trị viên",
                            PasswordHash = "$2a$11$rBnqmPnFjQFnXcJZCJRfUOZjHvBNOGKcMmJJKNJaGpGcBFQ9ABCDE",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("WebAPI.Models.Entities.AudioFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PoiId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PoiId");

                    b.ToTable("AudioFiles");
                });

            modelBuilder.Entity("WebAPI.Models.Entities.Poi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("RadiusMeters")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Pois");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Phở bò truyền thống từ 1970",
                            IsActive = true,
                            Latitude = 10.776899999999999,
                            Longitude = 106.7009,
                            Name = "Quán Phở Bà Dậu",
                            RadiusMeters = 30.0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bánh mì đặc sản nổi tiếng nhất phố",
                            IsActive = true,
                            Latitude = 10.7775,
                            Longitude = 106.7015,
                            Name = "Bánh Mì Hùng",
                            RadiusMeters = 30.0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chè truyền thống Nam Bộ",
                            IsActive = true,
                            Latitude = 10.778,
                            Longitude = 106.702,
                            Name = "Chè Bà Ba",
                            RadiusMeters = 30.0
                        });
                });

            modelBuilder.Entity("WebAPI.Models.Entities.Translation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PoiId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PoiId");

                    b.ToTable("Translations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Language = "vi",
                            PoiId = 1,
                            Text = "Chào mừng đến với Quán Phở Bà Dậu. Quán được thành lập từ năm 1970 với công thức phở bò truyền thống."
                        },
                        new
                        {
                            Id = 2,
                            Language = "en",
                            PoiId = 1,
                            Text = "Welcome to Pho Ba Dau restaurant, established in 1970 with traditional beef pho recipe."
                        },
                        new
                        {
                            Id = 3,
                            Language = "vi",
                            PoiId = 2,
                            Text = "Bánh Mì Hùng là địa điểm nổi tiếng nhất phố với hơn 30 năm kinh nghiệm làm bánh mì đặc sản."
                        },
                        new
                        {
                            Id = 4,
                            Language = "en",
                            PoiId = 2,
                            Text = "Banh Mi Hung is the most famous spot on the street with over 30 years of experience."
                        },
                        new
                        {
                            Id = 5,
                            Language = "vi",
                            PoiId = 3,
                            Text = "Chè Bà Ba phục vụ các loại chè truyền thống Nam Bộ được nấu theo công thức gia truyền."
                        },
                        new
                        {
                            Id = 6,
                            Language = "en",
                            PoiId = 3,
                            Text = "Che Ba Ba serves traditional Southern Vietnamese sweet desserts cooked with family recipes."
                        });
                });

            modelBuilder.Entity("WebAPI.Models.Entities.AudioFile", b =>
                {
                    b.HasOne("WebAPI.Models.Entities.Poi", "Poi")
                        .WithMany("AudioFiles")
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poi");
                });

            modelBuilder.Entity("WebAPI.Models.Entities.Translation", b =>
                {
                    b.HasOne("WebAPI.Models.Entities.Poi", "Poi")
                        .WithMany("Translations")
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poi");
                });

            modelBuilder.Entity("WebAPI.Models.Entities.Poi", b =>
                {
                    b.Navigation("AudioFiles");

                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
